[package]
name = "mx-chain-simulator-interface-config-rs"
version = "0.0.1"
edition = "2021"
include = [
    "src",
    "assets/**/*"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
include_dir = "0.7.3"